### ISSUE TITLE
Elected Officials - progress bar showing some extra text 

### ISSUE THREAD

**Issue by Dawnzar** [CityofOttawa/ckanext-ottawa#11]
1.Go to: http://data.ottawa.ca/dataset/elected-officials
2. Observe the progress bar below appears to unnecessary text.
![elected officials](https://cloud.githubusercontent.com/assets/5271253/8041808/f0bf6ada-0de8-11e5-9b37-8cdc936ea440.JPG)

**Comment by deniszgonjanin** [comment]
@Dawnzar ready for review

**Comment by Dawnzar** [comment]
Retested and resolved.
