### ISSUE TITLE
Accessibility_Useability : Incomplete text content is not understandable 

### ISSUE THREAD

**Issue by Dawnzar** [CityofOttawa/ckanext-ottawa#13]
WCAG 2.0 - Guideline 3.1 Readable: Make text readable and understandable, Level (A) compliance
1. Go to: http://data.ottawa.ca/dataset/elected-officials
2. Observe the incomplete text in the graph
   graphic below, text is incomplete.

Resolution: Please display the full title if possible for the sighted and non-sighted users.

![organizations_ incomplete text abbr](https://cloud.githubusercontent.com/assets/5271253/8042945/afbfb0aa-0df0-11e5-91c1-df0fc667d46a.JPG)

**Comment by deniszgonjanin** [comment]
@Dawnzar ready for review

**Comment by Dawnzar** [comment]
Retested and resolved.
